### ISSUE TITLE
Unclosed files/zombie processes

### ISSUE THREAD

**Issue by acroner** [mrkrd/thorns#10]
With python 3.5, using thorns.util.map for multiprocessing generates unclosed files and zombie processes (OSError: [Errno 24] Too many open files).

```
import thorns as th

def dummy(name):
        print(name)

backend = "multiprocessing"

for i in range(1,100):
        test = th.util.map(func = dummy,
                        space = {"name":"Dummy"},
                        backend = backend,
                        cache = "no",
                        kwargs = {})
        print("Iteration: {}".format(i))
```

inserting   `pool.close()` into maps._multiprocessing_map() after pooling is done fixes it.

**Comment by mrkrd** [comment]
> With python 3.5, [...]

Hi there, thorns is a library for Python 2.7 (as
stated in README/Installation) and there are
likely to be issues with Python 3.

FYI, I have no plans to upgrade it any time soon.

Depending on your usecase, you could go with
vanilla multiprocessing or dask or joblib.

Cheers,
Marek
