### ISSUE TITLE
TypeError: 'numpy.float64' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by SchraivogelS** [mrkrd/thorns#11]
https://github.com/mrkrd/thorns/blob/1fdc51012fc56d81963058841cbc54bfa083974c/thorns/waves.py#L171

Missing cast to int, should be 
n_samples = int(np.ceil(ramp * fs))
ramp_signal = np.linspace(0, 1, n_samples )

Python 3.9.7
numpy==1.22.2
thorns==1

**Comment by mrkrd** [comment]
done
